"""add phone number

Revision ID: 963c2c0f3e6e
Revises: 5e4f112bdd85
Create Date: 2022-06-29 14:14:44.270480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '963c2c0f3e6e'
down_revision = '5e4f112bdd85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
